/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import entidades.Cliente;
import entidades.Localidad;
import entidades.Provincia;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author German
 */
public class AltaCliente extends javax.swing.JFrame {

    /**
     * Creates new form AltaCliente
     */
    public AltaCliente() {
        AparienciaPantalla apa = new AparienciaPantalla();
        apa.cambiarApariencia("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        initComponents();
        this.cargarProvincias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ClienteNombrejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ClienteDireccionjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ClienteEmailjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CodPostjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ClienteTelefonojTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ClienteDNIjTextField = new javax.swing.JTextField();
        CancelarjButton = new javax.swing.JButton();
        GuardarjButton = new javax.swing.JButton();
        AyudajButton = new javax.swing.JButton();
        ClienteApellidojTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ClienteIDjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ProvinciasjComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        LocalidadesjComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        SexojComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        FecNacjDateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar nuevo cliente");

        jLabel1.setText("Nombre");

        jLabel2.setText("Dirección");

        jLabel3.setText("Email");

        jLabel4.setText("Código postal");

        CodPostjTextField.setEditable(false);

        jLabel5.setText("Telefono");

        ClienteTelefonojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ClienteTelefonojTextFieldKeyTyped(evt);
            }
        });

        jLabel6.setText("DNI");

        ClienteDNIjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ClienteDNIjTextFieldKeyTyped(evt);
            }
        });

        CancelarjButton.setText("Cancelar");
        CancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarjButtonActionPerformed(evt);
            }
        });

        GuardarjButton.setText("Guardar");
        GuardarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarjButtonActionPerformed(evt);
            }
        });

        AyudajButton.setText("Ayuda");
        AyudajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudajButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Apellido");

        ClienteIDjTextField.setVisible(false);
        ClienteIDjTextField.setEditable(false);

        jLabel7.setText("Provincia");

        ProvinciasjComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ProvinciasjComboBoxItemStateChanged(evt);
            }
        });

        jLabel10.setText("Localidad");

        jLabel9.setText("Sexo");

        SexojComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel11.setText("Fecha de nacimiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addGap(56, 56, 56)
                        .addComponent(ClienteApellidojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56)
                        .addComponent(ClienteTelefonojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56)
                        .addComponent(ClienteEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56)
                        .addComponent(CodPostjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(LocalidadesjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClienteNombrejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ClienteDNIjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProvinciasjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SexojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FecNacjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClienteIDjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClienteDireccionjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AyudajButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GuardarjButton)
                        .addGap(18, 18, 18)
                        .addComponent(CancelarjButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClienteIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ClienteDNIjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ClienteNombrejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ClienteApellidojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FecNacjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(SexojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ProvinciasjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(LocalidadesjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CodPostjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ClienteDireccionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ClienteEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ClienteTelefonojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarjButton)
                    .addComponent(GuardarjButton)
                    .addComponent(AyudajButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarjButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarjButtonActionPerformed

    private void ClienteDNIjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClienteDNIjTextFieldKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_ClienteDNIjTextFieldKeyTyped

    private void ClienteTelefonojTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClienteTelefonojTextFieldKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_ClienteTelefonojTextFieldKeyTyped

    private void AyudajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudajButtonActionPerformed
        abrirAyuda();
    }//GEN-LAST:event_AyudajButtonActionPerformed

    private void ProvinciasjComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ProvinciasjComboBoxItemStateChanged
        // TODO add your handling code here:
        this.cargarLocalidad();
    }//GEN-LAST:event_ProvinciasjComboBoxItemStateChanged

    private void GuardarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarjButtonActionPerformed
        // TODO add your handling code here:
        if (this.guardarOActualizar() != 0) {
            JOptionPane.showMessageDialog(null, "Cliente cargado correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "Ocurrio un error al cargar el cliente");
        }
    }//GEN-LAST:event_GuardarjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AyudajButton;
    private javax.swing.JButton CancelarjButton;
    private javax.swing.JTextField ClienteApellidojTextField;
    private javax.swing.JTextField ClienteDNIjTextField;
    private javax.swing.JTextField ClienteDireccionjTextField;
    private javax.swing.JTextField ClienteEmailjTextField;
    private javax.swing.JTextField ClienteIDjTextField;
    private javax.swing.JTextField ClienteNombrejTextField;
    private javax.swing.JTextField ClienteTelefonojTextField;
    private javax.swing.JTextField CodPostjTextField;
    private com.toedter.calendar.JDateChooser FecNacjDateChooser;
    private javax.swing.JButton GuardarjButton;
    private javax.swing.JComboBox<String> LocalidadesjComboBox;
    private javax.swing.JComboBox<String> ProvinciasjComboBox;
    private javax.swing.JComboBox<String> SexojComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void abrirAyuda() {
        try {
            //File file = new File(System.getProperty("user.dir") + "\\src\\ayuda\\Manual_Agregar_Cliente.pdf");
            //Desktop.getDesktop().open(file);

            if (Desktop.isDesktopSupported()) {
                File file = new File("Ayuda_Agregar_Cliente.pdf");
                if (!file.exists()) {
                    InputStream inputStream = ClassLoader.getSystemClassLoader()
                            .getResourceAsStream("ayuda/Ayuda_Agregar_Cliente.pdf");
                    OutputStream outputStream = new FileOutputStream(file);
                    byte[] buffer = new byte[1024];
                    int length;
                    while ((length = inputStream.read(buffer)) > 0) {
                        outputStream.write(buffer, 0, length);
                    }
                    outputStream.close();
                    inputStream.close();
                }
                Desktop.getDesktop().open(file);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se puedo abrir el archivo de ayuda");
        }
    }

    private void cargarProvincias() {
        ArrayList<Provincia> provincias = new ArrayList<>();
        try {
            provincias = new Provincia().listarProvincias();
            if (!provincias.isEmpty()) {
                for (int i = 0; i < provincias.size(); i++) {
                    ProvinciasjComboBox.addItem(provincias.get(i).getNombreProvincia());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ocurrio un error al cargar las provincias");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void cargarLocalidad() {
        ArrayList<Localidad> localidades = new ArrayList<Localidad>();
        int idprovincia;
        try {
            if (ProvinciasjComboBox.getItemCount() != 0) {
                if (ProvinciasjComboBox.getSelectedIndex() == 0) {
                    idprovincia = 1;
                } else {
                    idprovincia = ProvinciasjComboBox.getSelectedIndex();
                }
                localidades = new Localidad().listarLocalidades(idprovincia);
                if (!localidades.isEmpty()) {
                    LocalidadesjComboBox.removeAllItems();
                    for (int i = 0; i < localidades.size(); i++) {
                        LocalidadesjComboBox.addItem(localidades.get(i).getNombreLocalidad());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No existen localidades para la provincia seleccionada");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private boolean validar() {
        boolean valido = true;
        if (ClienteDNIjTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el dni del cliente");
            ClienteDNIjTextField.requestFocus();
            valido = false;
        } else if (ClienteDNIjTextField.getText().length() > 11) {
            JOptionPane.showMessageDialog(null, "DNI incorrecto");
            ClienteDNIjTextField.requestFocus();
            valido = false;
        } else if (ClienteNombrejTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre del cliente");
            ClienteNombrejTextField.requestFocus();
            valido = false;
        } else if (ClienteApellidojTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el apellido del cliente");
            ClienteApellidojTextField.requestFocus();
            valido = false;
        } else if (FecNacjDateChooser.getDateFormatString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una fecha de nacimiento");
            FecNacjDateChooser.requestFocus();
            valido = false;
        } else if (ClienteDireccionjTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una dirección");
            ClienteDireccionjTextField.requestFocus();
            valido = false;
        } else if (ClienteTelefonojTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un telefono");
            ClienteTelefonojTextField.requestFocus();
            valido = false;
        } else if (ClienteTelefonojTextField.getText().length() > 10) {
            JOptionPane.showMessageDialog(null, "Telefono invalido");
            ClienteTelefonojTextField.requestFocus();
            valido = false;
        }
        return valido;
    }

    public int guardarOActualizar() {
        int resultado = 0;
        try {
            Cliente cliente = new Cliente();
            if (validar()) {
                cliente.setDniCliente(Integer.parseInt(ClienteDNIjTextField.getText()));
                cliente.setNombreCliente(ClienteNombrejTextField.getText());
                cliente.setApellidoCliente(ClienteApellidojTextField.getText());
                cliente.setFechaNacimiento(FecNacjDateChooser.getDate());
                cliente.setSexo(SexojComboBox.getSelectedItem().toString());
                cliente.setLocalidad(new Localidad().obtenerLocalidad(LocalidadesjComboBox.getSelectedItem().toString()));
                cliente.setDireccionCliente(ClienteDireccionjTextField.getText());
                cliente.setMailCliente(ClienteEmailjTextField.getText());
                cliente.setTelefonoCliente(Integer.parseInt(ClienteTelefonojTextField.getText()));
            }
            if (ClienteIDjTextField.getText().isEmpty()) {
                resultado = cliente.altaCliente(cliente);
            } else {
                cliente.setIdCliente(Integer.parseInt(ClienteIDjTextField.getText()));
                resultado = cliente.modificarCliente(cliente);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return resultado;
    }
}
