/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import entidades.Localidad;
import entidades.Proveedor;
import entidades.Provincia;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author German
 */
public class AltaProveedor extends javax.swing.JFrame {

    /**
     * Creates new form AltaCliente
     */
    public AltaProveedor() {
        AparienciaPantalla apa = new AparienciaPantalla();
        apa.cambiarApariencia("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        initComponents();
        this.cargarProvincias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RazonSocialjTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DireccionjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EmailjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CodPostjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TelefonojTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CUITjTextField = new javax.swing.JTextField();
        CancelarjButton = new javax.swing.JButton();
        GuardarjButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ProvinciasjComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        LocalidadesjComboBox = new javax.swing.JComboBox<>();
        NombreFantasiajTextField = new javax.swing.JTextField();
        ProveedorIDjTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar nuevo proveedor - OSG");

        jLabel1.setText("Razon social");

        jLabel2.setText("Dirección");

        jLabel3.setText("Email");

        jLabel4.setText("Código postal");

        CodPostjTextField.setEditable(false);
        CodPostjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodPostjTextFieldKeyTyped(evt);
            }
        });

        jLabel5.setText("Telefono");

        TelefonojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonojTextFieldKeyTyped(evt);
            }
        });

        jLabel6.setText("CUIT");

        CUITjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CUITjTextFieldKeyTyped(evt);
            }
        });

        CancelarjButton.setText("Cancelar");
        CancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarjButtonActionPerformed(evt);
            }
        });

        GuardarjButton.setText("Guardar");
        GuardarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarjButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre de fantasia");

        jLabel7.setText("Provincia");

        ProvinciasjComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ProvinciasjComboBoxItemStateChanged(evt);
            }
        });

        jLabel10.setText("Localidad");

        LocalidadesjComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LocalidadesjComboBoxItemStateChanged(evt);
            }
        });

        ProveedorIDjTextField.setVisible(false);
        ProveedorIDjTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56)
                        .addComponent(TelefonojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56)
                        .addComponent(EmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addGap(56, 56, 56)
                        .addComponent(CodPostjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(ProvinciasjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(LocalidadesjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CUITjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RazonSocialjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(NombreFantasiajTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DireccionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ProveedorIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GuardarjButton)
                        .addGap(18, 18, 18)
                        .addComponent(CancelarjButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CUITjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(RazonSocialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(NombreFantasiajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ProvinciasjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(LocalidadesjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CodPostjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DireccionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TelefonojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarjButton)
                    .addComponent(GuardarjButton)
                    .addComponent(ProveedorIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarjButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarjButtonActionPerformed

    private void CUITjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CUITjTextFieldKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_CUITjTextFieldKeyTyped

    private void CodPostjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodPostjTextFieldKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_CodPostjTextFieldKeyTyped

    private void TelefonojTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonojTextFieldKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_TelefonojTextFieldKeyTyped

    private void ProvinciasjComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ProvinciasjComboBoxItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.cargarLocalidad();
        }
    }//GEN-LAST:event_ProvinciasjComboBoxItemStateChanged

    private void GuardarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarjButtonActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Guardar proveedor?");
            if (respuesta == JOptionPane.YES_OPTION) {
                guardarOActualizarProveedor();
                this.dispose();
                new GestionDeProveedores().setVisible(true);
            }
        }
    }//GEN-LAST:event_GuardarjButtonActionPerformed

    private void LocalidadesjComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LocalidadesjComboBoxItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            try {
                Localidad localidad = new Localidad().obtenerLocalidad(LocalidadesjComboBox.getSelectedItem().toString());
                CodPostjTextField.setText(Integer.toString(localidad.getCodigoPosta()));
            } catch (Exception ex) {
                Logger.getLogger(AltaProveedor.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_LocalidadesjComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField CUITjTextField;
    private javax.swing.JButton CancelarjButton;
    protected javax.swing.JTextField CodPostjTextField;
    protected javax.swing.JTextField DireccionjTextField;
    protected javax.swing.JTextField EmailjTextField;
    private javax.swing.JButton GuardarjButton;
    protected javax.swing.JComboBox<String> LocalidadesjComboBox;
    protected javax.swing.JTextField NombreFantasiajTextField;
    protected javax.swing.JTextField ProveedorIDjTextField;
    protected javax.swing.JComboBox<String> ProvinciasjComboBox;
    protected javax.swing.JTextField RazonSocialjTextField;
    protected javax.swing.JTextField TelefonojTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void cargarProvincias() {
        ArrayList<Provincia> provincias = new ArrayList<>();
        try {
            provincias = new Provincia().listarProvincias();
            if (!provincias.isEmpty()) {
                for (int i = 0; i < provincias.size(); i++) {
                    ProvinciasjComboBox.addItem(provincias.get(i).getNombreProvincia());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ocurrio un error al cargar las provincias");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void cargarLocalidad() {
        ArrayList<Localidad> localidades = new ArrayList<Localidad>();
        int idprovincia;
        try {
            if (ProvinciasjComboBox.getItemCount() != 0) {
                if (ProvinciasjComboBox.getSelectedIndex() == 0) {
                    idprovincia = 1;
                } else {
                    idprovincia = ProvinciasjComboBox.getSelectedIndex();
                }
                localidades = new Localidad().listarLocalidades(idprovincia);
                if (!localidades.isEmpty()) {
                    LocalidadesjComboBox.removeAllItems();
                    for (int i = 0; i < localidades.size(); i++) {
                        LocalidadesjComboBox.addItem(localidades.get(i).getNombreLocalidad());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No existen localidades para la provincia seleccionada");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private boolean validar() {
        boolean valido = true;
        if (CUITjTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha ingresado un CUIT");
            CUITjTextField.requestFocus();
            valido = false;
        } else if (CUITjTextField.getText().length() != 11) {
            JOptionPane.showMessageDialog(null, "El CUIT debe contener 11 numeros");
            CUITjTextField.requestFocus();
            valido = false;
        } else if (RazonSocialjTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha ingresado la razon social del proveedor");
            RazonSocialjTextField.requestFocus();
            valido = false;
        } else if (NombreFantasiajTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha ingresado el nombre de fantasia del proveedor");
            NombreFantasiajTextField.requestFocus();
            valido = false;
        } else if (DireccionjTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una dirección");
            DireccionjTextField.requestFocus();
            valido = false;
        } else if (TelefonojTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un telefono de contacto");
            TelefonojTextField.requestFocus();
            valido = false;
        }
        return valido;
    }

    private void guardarOActualizarProveedor() {
        int resultado;
        Proveedor proveedor = new Proveedor();
        try {
            proveedor.setCuit(Long.parseLong(CUITjTextField.getText()));
            proveedor.setRazonSocial(RazonSocialjTextField.getText());
            proveedor.setNombreFantasia(NombreFantasiajTextField.getText());
            proveedor.setLocalidad(new Localidad().obtenerLocalidad(LocalidadesjComboBox.getSelectedItem().toString()));
            proveedor.setDireccionProveedor(DireccionjTextField.getText());
            proveedor.setMailProveedor(EmailjTextField.getText());
            proveedor.setTelefonoProveedor(Long.parseLong(TelefonojTextField.getText()));
            if (ProveedorIDjTextField.getText().isEmpty()) {
                resultado = proveedor.altaProveedor(proveedor);
            } else {
                proveedor.setIdProveedor(Integer.parseInt(ProveedorIDjTextField.getText()));
                resultado = proveedor.modificarProveedor(proveedor);
            }
            if (resultado != 0) {
                JOptionPane.showMessageDialog(null, "Proveedor guardado exitosamente");
                GestionDeProveedores panta = new GestionDeProveedores();
                panta.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "El proveedor no pudo guardarse");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
}
