/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pantallas;

import entidades.Cliente;
import entidades.Producto;
import gestores.GestorCliente;
import gestores.GestorPresupuesto;
import gestores.GestorProducto;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import static java.lang.Long.parseLong;
import static java.lang.String.valueOf;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author German
 */
public class VentaEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form AltaPresupuesto
     */
    public VentaEmpleado() {
        AparienciaPantalla apa = new AparienciaPantalla();
        apa.cambiarApariencia("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        initComponents();
        codigoBarra.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        BeliminarProducto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        detalleProducto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        precioTotal = new javax.swing.JTextField();
        listaCliente = new javax.swing.JComboBox();
        nombreCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        codigoBarra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cantidadRenglon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jbClienteCasual = new javax.swing.JButton();
        descripcionProducto = new javax.swing.JTextField();
        listaProducto = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        descripcionAgregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        guardarPresup = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        precioTotal1 = new javax.swing.JTextField();

        jRadioButton3.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva venta - OSG");

        BeliminarProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BeliminarProducto.setText("Quitar producto seleccionado");
        BeliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliminarProductoActionPerformed(evt);
            }
        });

        detalleProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(detalleProducto);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Total");

        precioTotal.setEditable(false);
        precioTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        precioTotal.setBorder(null);

        listaCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listaCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaClienteItemStateChanged(evt);
            }
        });

        nombreCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));
        nombreCliente.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nombreClienteCaretUpdate(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cliente");

        codigoBarra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        codigoBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        codigoBarra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoBarraFocusGained(evt);
            }
        });
        codigoBarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoBarraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoBarraKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Codigo");

        cantidadRenglon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cantidadRenglon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidadRenglon.setText("1");
        cantidadRenglon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cantidadRenglon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadRenglonKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("x");

        jbClienteCasual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbClienteCasual.setText("Cliente casual");
        jbClienteCasual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClienteCasualActionPerformed(evt);
            }
        });

        descripcionProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descripcionProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        descripcionProducto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                descripcionProductoCaretUpdate(evt);
            }
        });

        listaProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Descripción");

        descripcionAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descripcionAgregar.setText("Agregar");
        descripcionAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionAgregarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Producto");

        guardarPresup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        guardarPresup.setText("Presupuesto");
        guardarPresup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPresupActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("VENTA");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Pago");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("El total a pagar es de");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("con el medio de pago");

        precioTotal1.setEditable(false);
        precioTotal1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BeliminarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(precioTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(codigoBarra)
                                    .addComponent(descripcionProducto)
                                    .addComponent(listaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cantidadRenglon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(descripcionAgregar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(31, 31, 31)
                                .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(listaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbClienteCasual)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardarPresup)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbClienteCasual))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(codigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(descripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cantidadRenglon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descripcionAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BeliminarProducto)
                    .addComponent(precioTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guardarPresup)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel2)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(precioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descripcionAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionAgregarActionPerformed

    }//GEN-LAST:event_descripcionAgregarActionPerformed

    private void descripcionProductoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_descripcionProductoCaretUpdate
        buscarProducto();
    }//GEN-LAST:event_descripcionProductoCaretUpdate

    private void jbClienteCasualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClienteCasualActionPerformed

        nombreCliente.setText("");
        listaCliente.removeAllItems();
    }//GEN-LAST:event_jbClienteCasualActionPerformed

    private void cantidadRenglonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadRenglonKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_cantidadRenglonKeyTyped

    private void codigoBarraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoBarraKeyTyped

    }//GEN-LAST:event_codigoBarraKeyTyped

    private void codigoBarraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoBarraKeyReleased

    }//GEN-LAST:event_codigoBarraKeyReleased

    private void codigoBarraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoBarraFocusGained
        descripcionProducto.setText(null);
        listaProducto.removeAllItems();
    }//GEN-LAST:event_codigoBarraFocusGained

    private void nombreClienteCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nombreClienteCaretUpdate
        buscarMientrasEscribe();
    }//GEN-LAST:event_nombreClienteCaretUpdate

    private void listaClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaClienteItemStateChanged
        if (listaCliente.getSelectedItem()!=null){
            Cliente c = (Cliente) listaCliente.getSelectedItem();
        }
    }//GEN-LAST:event_listaClienteItemStateChanged

    private void guardarPresupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPresupActionPerformed
        try {
            detalleProducto.print();
        } catch (PrinterException ex) { 
            
        }
    }//GEN-LAST:event_guardarPresupActionPerformed

    private void BeliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliminarProductoActionPerformed
        eliminarItemProducto();
        actualizarTotal();
    }//GEN-LAST:event_BeliminarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BeliminarProducto;
    private javax.swing.JTextField cantidadRenglon;
    private javax.swing.JTextField codigoBarra;
    private javax.swing.JButton descripcionAgregar;
    private javax.swing.JTextField descripcionProducto;
    private javax.swing.JTable detalleProducto;
    private javax.swing.JButton guardarPresup;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbClienteCasual;
    private javax.swing.JComboBox listaCliente;
    private javax.swing.JComboBox listaProducto;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTextField precioTotal;
    private javax.swing.JTextField precioTotal1;
    // End of variables declaration//GEN-END:variables
    private String paraBuscar="";
    private Cliente cli;
    private Producto pro;
    private double iva = (double) 1.21;
    
    private void buscarProducto(){
        paraBuscar = descripcionProducto.getText();
        if (GestorProducto.ConsultaPorDescripcion(paraBuscar).size() != 0){
            listaProducto.removeAllItems();;
            for (int i = 0; i < GestorProducto.ConsultaPorDescripcion(paraBuscar).size();i++){
                pro = new Producto(GestorProducto.ConsultaPorDescripcion(paraBuscar).get(i).getCodigoDeProducto(), 
                        GestorProducto.ConsultaPorDescripcion(paraBuscar).get(i).getNombreProducto(), 
                        GestorProducto.ConsultaPorDescripcion(paraBuscar).get(i).getPrecioContado(), 
                        GestorProducto.ConsultaPorDescripcion(paraBuscar).get(i).getPrecioDebito(),
                        GestorProducto.ConsultaPorDescripcion(paraBuscar).get(i).getPrecioCredito(),
                        GestorProducto.ConsultaPorDescripcion(paraBuscar).get(i).getStockProducto());
                listaProducto.addItem(pro);                
            }
        }
    }

    private void buscarMientrasEscribe() {
        paraBuscar = nombreCliente.getText();
        if (GestorCliente.ConsultaPorDescripcion(paraBuscar).size() != 0) {
            listaCliente.removeAllItems();
            for (int i = 0; i < GestorCliente.ConsultaPorDescripcion(paraBuscar).size(); i++) {
                cli = new Cliente(GestorCliente.ConsultaPorDescripcion(paraBuscar).get(i).getIdCliente(),
                    GestorCliente.ConsultaPorDescripcion(paraBuscar).get(i).getNombreCliente(),
                    GestorCliente.ConsultaPorDescripcion(paraBuscar).get(i).getDireccionCliente(),
                    GestorCliente.ConsultaPorDescripcion(paraBuscar).get(i).getCodigoPostalCliente(),
                    GestorCliente.ConsultaPorDescripcion(paraBuscar).get(i).getTelefonoCliente(),
                    GestorCliente.ConsultaPorDescripcion(paraBuscar).get(i).getDniCuilCuit(),
                    GestorCliente.ConsultaPorDescripcion(paraBuscar).get(i).getMailCliente());
                listaCliente.addItem(cli);
            }
        }
    }

    private void actualizarTotal() {
        DefaultTableModel tabla = (DefaultTableModel) detalleProducto.getModel();
        double suma = 0;
        for (int i = 0; i<tabla.getRowCount(); i++){
            suma += parseFloat(tabla.getValueAt(i,5).toString());
        }
        try{
            precioTotal.setText("$ " + valueOf(suma).substring(0, valueOf(suma).indexOf(".")+3));
        }catch (StringIndexOutOfBoundsException e){
            precioTotal.setText("$ " + valueOf(suma));
        }
    }

    private void eliminarItemProducto() {
        DefaultTableModel tabla = (DefaultTableModel) detalleProducto.getModel();
        if (tabla.getRowCount()!=0){
            try{
                tabla.removeRow(detalleProducto.getSelectedRow());
            }catch (ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null, "Debe seleccionar el producto"
                        + " a eliminar");
            }
        }
    }



    private int crearPresupuesto() {
        int status = 0;
        DefaultTableModel tabla = (DefaultTableModel) detalleProducto.getModel();
        int nuevoPresupuesto;
        
        Date fecha = new Date();      
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fecha); 
        calendar.add(Calendar.DAY_OF_YEAR, 30); 
        SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd");
        String fechaVigencia = formateador.format(calendar.getTime());
        
        int codCliente = 0;
        if (listaCliente.getSelectedItem()!=null){
            Cliente c = (Cliente) listaCliente.getSelectedItem();
            codCliente = c.getIdCliente();
        }
        
        if(codCliente!=0){
            nuevoPresupuesto = GestorPresupuesto.agregarPresupuesto(codCliente, fechaVigencia);
        }else{
            nuevoPresupuesto = GestorPresupuesto.agregarPresupuesto(fechaVigencia);
        }
        
        if (nuevoPresupuesto!=0){
            ArrayList<String> renglon = new ArrayList();
            for (int i = 0; i<tabla.getRowCount(); i++){
                long codiProd = parseLong(tabla.getValueAt(i,0).toString());
                int cantidad = parseInt(tabla.getValueAt(i,2).toString());
                double precioRenglon = parseFloat(tabla.getValueAt(i,5).toString());
                String precioUnitarioConIVa = valueOf(parseFloat(tabla.getValueAt(i,3).toString())*iva);
                
                GestorPresupuesto.productoPresupuesto(nuevoPresupuesto, codiProd, cantidad, precioRenglon);

                String descripcionProd = tabla.getValueAt(i,1).toString();
                try{
                    descripcionProd= tabla.getValueAt(i,1).toString().substring(0, 30);
                }catch (StringIndexOutOfBoundsException e){
                }
                
                renglon.add(descripcionProd + "\n\r x " + tabla.getValueAt(i,2).toString()
                + "\t\t" + precioUnitarioConIVa + " = " + tabla.getValueAt(i,5).toString());
            }
            imprimir(renglon,precioTotal.getText(), nuevoPresupuesto);
            status = nuevoPresupuesto;
        }
    return status;
    }
    
    private void imprimir(ArrayList<String> renglonPresupuesto, String total, int nuPresup){
        
        DocFlavor byar = DocFlavor.BYTE_ARRAY.AUTOSENSE;
        
        //Aqui selecciona tu impresora, el ejemplo tomará la impresora predeterminada.
        PrintService impresoraDefa = PrintServiceLookup.lookupDefaultPrintService();
        DocPrintJob trabajoImpresora = impresoraDefa.createPrintJob();
        
        String detalle = "---------------------------\n\r"
                + "Abracadabra Cotillon de \n\r"
                + "Demichelis Cintia \n\r" 
                + "CUIT: 27-29759893-2 \n\r"
                + "Domicilio: Saenz Peña 1240 \n\r"
                + "Telefono: 03437-15440136 \n\n\r"
                + "Ticket Numero: " + valueOf(nuPresup)
                + "\n\r DETALLE: \n\r";
        
        
        for (int i=0; i<renglonPresupuesto.size();i++){
            detalle += renglonPresupuesto.get(i) + "\n\r";
        }
        
        detalle += "\n Monto Total: " + total;
        
        String mostrar = detalle.replaceAll("á","a").replaceAll("é", "e")
                .replaceAll("í", "i").replaceAll("ó", "o").replaceAll("ú", "u")
                .replaceAll("ü", "u").replaceAll("ñ", "n");
                
        byte[] bytes = mostrar.getBytes();
        
        Doc doc = new SimpleDoc(bytes, byar, null);
        
        try {
            trabajoImpresora.print(doc, null);
        } catch (PrintException e) {
            System.out.println(e);
        }
    }

}
   
